name: pre-commit

on:
  push:
    branches: main
  pull_request:
    branches: dev
  workflow_dispatch:

jobs:
  pre-commit:
    uses: cpp-linter/.github/.github/workflows/pre-commit.yml@main